### ISSUE TITLE
ValueError: Length mismatch: Expected axis has 149 elements, new values have 197 elements

### ISSUE THREAD

**Issue by arshi-16** [AleksLi1/Global_Growth_Trend_Timing#1]
```
PS C:\Users\arshi\PycharmProjects\pythonProject> python.exe .\GTT_Main.py
[*********************100%***********************]  2 of 2 completed
Traceback (most recent call last):
  File "C:\Users\arshi\PycharmProjects\pythonProject\GTT_Main.py", line 66, in <module>
    result_df.index = trading_month_start
  File "C:\Users\arshi\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\core\generic.py", line 5500, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 70, in pandas._libs.properties.AxisProperty.__set__
  File "C:\Users\arshi\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\core\generic.py", line 766, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "C:\Users\arshi\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\core\internals\managers.py", line 216, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "C:\Users\arshi\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\core\internals\base.py", line 57, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 149 elements, new values have 197 elements
PS C:\Users\arshi\PycharmProjects\pythonProject> python.exe .\GTT_Main.py
[*********************100%***********************]  2 of 2 completed
Traceback (most recent call last):
  File "C:\Users\arshi\PycharmProjects\pythonProject\GTT_Main.py", line 66, in <module>
    result_df.index = trading_month_start
  File "C:\Users\arshi\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\core\generic.py", line 5500, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 70, in pandas._libs.properties.AxisProperty.__set__
  File "C:\Users\arshi\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\core\generic.py", line 766, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "C:\Users\arshi\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\core\internals\managers.py", line 216, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "C:\Users\arshi\PycharmProjects\pythonProject\venv\lib\site-packages\pandas\core\internals\base.py", line 57, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 149 elements, new values have 197 elements
```

**Comment by AleksLi1** [comment]
Hi Arshi, thanks for reporting this issue. It seems that the problem stems from yahoo finance deprecating their access to price data prior to 2009. Will let you know when the issue is fixed.

**Comment by AleksLi1** [comment]
Hi Arshi, just to let you know that the model should be working fine now. Let me know if you experience any more issues.
